---
title: Lab 4
author: Thomas and Saleh
output: pdf_document
---

```{r library}
library(leaps)
```


```{r betty_setup}
n <- 100
sig <- 1
b <- c(1.5, -2,-0.5, 1)
set.seed(10)
x <- sort(round(runif(n, -2, 2), 2))
eps <- rnorm(n, 0, sig)
ones <- vector(length = n) + 1
x2 <- x^2
x3 <- x^3
xmat <- cbind(ones, x, x2, x3)
fx <- xmat %*% b
y <- fx + eps
data <- data.frame(x, y)
plot(x, fx, type = 'l', lwd = 2, ylim = c(-5, 5),
     main = 'True relationship between y and x with generated sample')
points(x, y, pch=19)
```


## One

$$
y = 1.5 - 2 x - 0.5 x^2 + x^3 + \epsilon
$$

## Two

```{r two}
data[, 3] <- data[, 1]^2
data[, 4] <- data[, 1]^3
data[, 5] <- data[, 1]^4
data[, 6] <- data[, 1]^5
data[, 7] <- data[, 1]^6
data[, 8] <- data[, 1]^7
data[, 9] <- data[, 1]^8
data[, 10] <- data[, 1]^9
data[, 11] <- data[, 1]^10

sub <- leaps::regsubsets(as.matrix(data[, -2]), as.matrix(data[,2]))
our_sum <- summary(sub)

fourth <- coef(sub, 4)
third <- coef(sub, 3)
```

### a

According to Cp criterion the 4th model is the best with a cp of **`r round(our_sum$cp[4], 2)`**
this model is...
$$
y = `r round(fourth[1], digits = 2)` + `r round(fourth[2], digits = 2)` x + `r round(fourth[3], digits = 2)` x^2 + `r round(fourth[4], digits = 2)` x^3 + `r round(fourth[5], digits = 2)` x^4
$$

### b

According to the BIC the third model is the best with a BIC of **`r round(our_sum$bic[3], 2)`**
this model is...
$$
y = `r round(third[1], digits = 2)` + `r round(third[2], digits = 2)` x + `r round(third[3], digits = 2)` x^2 + `r round(third[4], digits = 2)` x^3
$$

### c

According to adjusted r^2 the fourth model is the best with a adjr^2 of **`r round(our_sum$adjr2[4], 2)`**
this model is...
$$
y = `r round(fourth[1], digits = 2)` + `r round(fourth[2], digits = 2)` x + `r round(fourth[3], digits = 2)` x^2 + `r round(fourth[4], digits = 2)` x^3 + `r round(fourth[5], digits = 2)` x^4
$$





